// <auto-generated />
using System;
using AegisScore.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AegisScore.Infrastructure.Migrations
{
    [DbContext(typeof(AegisScoreDbContext))]
    [Migration("20260716212615_AddIntelligenceJsonToControlState")]
    partial class AddIntelligenceJsonToControlState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AegisScore.Domain.ActionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("HowToImplement")
                        .HasColumnType("text");

                    b.Property<string>("ResponsibleArea")
                        .HasColumnType("text");

                    b.Property<string>("ResponsiblePerson")
                        .HasColumnType("text");

                    b.Property<Guid>("RiskId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Treatment")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RiskId");

                    b.HasIndex("TenantId", "RiskId");

                    b.ToTable("ActionPlans");
                });

            modelBuilder.Entity("AegisScore.Domain.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessmentScopeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RespondedById")
                        .HasColumnType("text");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentScopeId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("AegisScore.Domain.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FrameworkVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("AegisScore.Domain.AssessmentScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessProcessId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessUnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("TenantId", "AssessmentId");

                    b.ToTable("Scopes");
                });

            modelBuilder.Entity("AegisScore.Domain.AssessmentTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessmentScopeId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssigneeId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentScopeId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("AegisScore.Domain.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BusinessProcessId")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Criticality")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DiscoverySource")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OwnerName")
                        .HasColumnType("text");

                    b.Property<int?>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<string>("RiskRationaleJson")
                        .HasColumnType("text");

                    b.Property<double?>("RiskScore")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("RiskScoredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BusinessProcessId");

                    b.HasIndex("TenantId", "Category");

                    b.HasIndex("TenantId", "Criticality");

                    b.HasIndex("TenantId", "ExternalRef")
                        .IsUnique()
                        .HasFilter("\"ExternalRef\" IS NOT NULL");

                    b.HasIndex("TenantId", "RiskLevel");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("AegisScore.Domain.AssetDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DiscoverySource")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SourceAssetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetAssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SourceAssetId");

                    b.HasIndex("TargetAssetId");

                    b.HasIndex("TenantId", "SourceAssetId", "TargetAssetId", "Type")
                        .IsUnique();

                    b.ToTable("AssetDependencies", t =>
                        {
                            t.HasCheckConstraint("CK_AssetDependency_NoSelfLoop", "\"SourceAssetId\" <> \"TargetAssetId\"");
                        });
                });

            modelBuilder.Entity("AegisScore.Domain.AssetThreatExposure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiscoverySource")
                        .HasColumnType("integer");

                    b.Property<string>("EvidenceJson")
                        .HasColumnType("text");

                    b.Property<int>("Likelihood")
                        .HasColumnType("integer");

                    b.Property<string>("MitigatingSubcategoryCode")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ThreatId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ThreatId");

                    b.HasIndex("TenantId", "AssetId", "ThreatId")
                        .IsUnique();

                    b.ToTable("AssetThreatExposures");
                });

            modelBuilder.Entity("AegisScore.Domain.BlastRadiusAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("BlastRadiusScore")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ComputedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FactorsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ImpactedAssetCount")
                        .HasColumnType("integer");

                    b.Property<int>("ImpactedProcessCount")
                        .HasColumnType("integer");

                    b.Property<int>("MaxDepth")
                        .HasColumnType("integer");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("RootAssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScenarioThreatId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Trigger")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RootAssetId");

                    b.HasIndex("ScenarioThreatId");

                    b.HasIndex("TenantId", "RootAssetId");

                    b.ToTable("BlastRadiusAssessments");
                });

            modelBuilder.Entity("AegisScore.Domain.BlastRadiusImpactNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Distance")
                        .HasColumnType("integer");

                    b.Property<Guid>("ImpactedAssetId")
                        .HasColumnType("uuid");

                    b.Property<int>("PathStrength")
                        .HasColumnType("integer");

                    b.Property<double>("PropagatedImpact")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("ImpactedAssetId");

                    b.HasIndex("TenantId", "AssessmentId");

                    b.ToTable("BlastRadiusImpactNodes");
                });

            modelBuilder.Entity("AegisScore.Domain.BusinessProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessCategory")
                        .HasColumnType("text");

                    b.Property<int>("ProcessValue")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("AegisScore.Domain.BusinessUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManagerEmail")
                        .HasColumnType("text");

                    b.Property<string>("ManagerName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("BusinessUnits");
                });

            modelBuilder.Entity("AegisScore.Domain.ConnectorConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AuthType")
                        .HasColumnType("integer");

                    b.Property<int>("Capability")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("EncryptedSettings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LastStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<int>("SyncIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Connectors");
                });

            modelBuilder.Entity("AegisScore.Domain.DocumentControlMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AnalystConfirmed")
                        .HasColumnType("boolean");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Evidence")
                        .HasColumnType("text");

                    b.Property<Guid>("GovernanceDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubcategoryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GovernanceDocumentId");

                    b.HasIndex("TenantId", "GovernanceDocumentId");

                    b.HasIndex("TenantId", "SubcategoryCode");

                    b.ToTable("DocumentControlMappings");
                });

            modelBuilder.Entity("AegisScore.Domain.Evidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiSummary")
                        .HasColumnType("text");

                    b.Property<Guid?>("AssessmentScopeId")
                        .HasColumnType("uuid");

                    b.Property<string>("BlobRef")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SubcategoryCode")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Uri")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentScopeId");

                    b.HasIndex("TenantId");

                    b.ToTable("Evidence");
                });

            modelBuilder.Entity("AegisScore.Domain.EvidenceSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConnectorConfigId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JsonValue")
                        .HasColumnType("text");

                    b.Property<string>("MappedSubcategoryCodes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double?>("NumericValue")
                        .HasColumnType("double precision");

                    b.Property<int?>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("SignalKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SignalKey", "CollectedAt");

                    b.ToTable("Signals");
                });

            modelBuilder.Entity("AegisScore.Domain.FrameworkVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FrameworkVersions");
                });

            modelBuilder.Entity("AegisScore.Domain.GovernanceDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalysisError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("AnalysisQueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AnalysisStatus")
                        .HasColumnType("integer");

                    b.Property<string>("AnalysisSummary")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DocumentDate")
                        .HasColumnType("date");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ModelUsed")
                        .HasColumnType("text");

                    b.Property<string>("Sha256")
                        .HasColumnType("text");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceReference")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StorageUri")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Sha256")
                        .IsUnique()
                        .HasFilter("\"Sha256\" IS NOT NULL");

                    b.ToTable("GovernanceDocuments");
                });

            modelBuilder.Entity("AegisScore.Domain.GrcInterviewMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GrcInterviewSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetSubcategoryCode")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GrcInterviewSessionId");

                    b.HasIndex("TenantId", "SessionId");

                    b.ToTable("GrcInterviewMessages");
                });

            modelBuilder.Entity("AegisScore.Domain.GrcInterviewSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssessmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetSubcategoryCodes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("GrcInterviewSessions");
                });

            modelBuilder.Entity("AegisScore.Domain.IcrScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Band")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FactorsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<string>("SubjectRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubjectType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("IcrScores");
                });

            modelBuilder.Entity("AegisScore.Domain.IcrWeightProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AssetCriticality")
                        .HasColumnType("double precision");

                    b.Property<double>("BusinessImpact")
                        .HasColumnType("double precision");

                    b.Property<double>("ControlEffectiveness")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OverdueActionPlan")
                        .HasColumnType("double precision");

                    b.Property<double>("RecentExploitation")
                        .HasColumnType("double precision");

                    b.Property<double>("RegulatoryExposure")
                        .HasColumnType("double precision");

                    b.Property<double>("TechnicalSeverity")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("IcrWeightProfiles");
                });

            modelBuilder.Entity("AegisScore.Domain.IdentifiedRisk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssessmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cause")
                        .HasColumnType("text");

                    b.Property<string>("Consequence")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("IdentifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OriginInterviewSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("PromotedToRisk")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RiskId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubcategoryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SubcategoryCode");

                    b.ToTable("IdentifiedRisks");
                });

            modelBuilder.Entity("AegisScore.Domain.MaturityLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FrameworkVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkVersionId");

                    b.ToTable("MaturityLevels");
                });

            modelBuilder.Entity("AegisScore.Domain.MaturitySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CurrentScore")
                        .HasColumnType("double precision");

                    b.Property<double>("Gap")
                        .HasColumnType("double precision");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("RefCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TargetScore")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MaturitySnapshots");
                });

            modelBuilder.Entity("AegisScore.Domain.NistCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FunctionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FunctionId", "Code")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("AegisScore.Domain.NistFunction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FrameworkVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkVersionId", "Code")
                        .IsUnique();

                    b.ToTable("Functions");
                });

            modelBuilder.Entity("AegisScore.Domain.NistSubcategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImplementationExamples")
                        .HasColumnType("text");

                    b.Property<string>("InformativeReferences")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("MaxScorePoints")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Code")
                        .IsUnique();

                    b.ToTable("Subcategories");
                });

            modelBuilder.Entity("AegisScore.Domain.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnswerType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Guidance")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubcategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThemeGroup")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("AegisScore.Domain.RemediationAdvisory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentedRisk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubcategoryCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("TechnicalSteps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SubcategoryCode");

                    b.ToTable("RemediationAdvisories");
                });

            modelBuilder.Entity("AegisScore.Domain.Risk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BusinessProcessId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BusinessUnitId")
                        .HasColumnType("uuid");

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FocalPoint")
                        .HasColumnType("text");

                    b.Property<string>("ManagerName")
                        .HasColumnType("text");

                    b.Property<Guid?>("OriginEvidenceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OriginExposureId")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginSubcategoryCode")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Threats")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Vulnerabilities")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("Risks");
                });

            modelBuilder.Entity("AegisScore.Domain.RiskAppetite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThresholdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("RiskAppetites");
                });

            modelBuilder.Entity("AegisScore.Domain.RiskEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Impact")
                        .HasColumnType("integer");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<int>("Probability")
                        .HasColumnType("integer");

                    b.Property<int>("ProcessValue")
                        .HasColumnType("integer");

                    b.Property<Guid>("RiskId")
                        .HasColumnType("uuid");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RiskId");

                    b.HasIndex("TenantId", "RiskId");

                    b.ToTable("RiskEvaluations");
                });

            modelBuilder.Entity("AegisScore.Domain.SignalMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capability")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FrameworkVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScoringHint")
                        .HasColumnType("text");

                    b.Property<string>("SignalKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubcategoryCodes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("SignalMappings");
                });

            modelBuilder.Entity("AegisScore.Domain.SubcategoryCoverage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EvidenceSource")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastEvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("OriginDocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OriginInterviewSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SubcategoryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SubcategoryCode")
                        .IsUnique();

                    b.ToTable("SubcategoryCoverages");
                });

            modelBuilder.Entity("AegisScore.Domain.SubcategoryEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessmentScopeId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentComments")
                        .HasColumnType("text");

                    b.Property<int?>("CurrentLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentScore")
                        .HasColumnType("integer");

                    b.Property<int>("EvaluatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("EvidenceRefs")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Rationale")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedById")
                        .HasColumnType("text");

                    b.Property<Guid>("SubcategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetComments")
                        .HasColumnType("text");

                    b.Property<int?>("TargetLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentScopeId");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("AegisScore.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("AegisScore.Domain.TenantControlState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiEvidence")
                        .HasColumnType("text");

                    b.Property<string>("ChecksJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentScore")
                        .HasColumnType("integer");

                    b.Property<string>("IntelligenceJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastEvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastVerdictSource")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubcategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubcategoryId");

                    b.HasIndex("TenantId", "SubcategoryId")
                        .IsUnique();

                    b.ToTable("TenantControlStates");
                });

            modelBuilder.Entity("AegisScore.Domain.TenantScoreSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalAchievedScore")
                        .HasColumnType("integer");

                    b.Property<int>("TotalMaxScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SnapshotDate")
                        .IsUnique();

                    b.ToTable("TenantScoreSnapshots");
                });

            modelBuilder.Entity("AegisScore.Domain.Threat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("BaseSeverity")
                        .HasColumnType("double precision");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("KnownExploited")
                        .HasColumnType("boolean");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("Tactic")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code", "Source")
                        .IsUnique();

                    b.ToTable("Threats");
                });

            modelBuilder.Entity("AegisScore.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AegisScore.Domain.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "Token")
                        .IsUnique();

                    b.HasIndex("TenantId", "UserId");

                    b.ToTable("UserRefreshTokens");
                });

            modelBuilder.Entity("AegisScore.Domain.ActionPlan", b =>
                {
                    b.HasOne("AegisScore.Domain.Risk", null)
                        .WithMany("ActionPlans")
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AegisScore.Domain.Answer", b =>
                {
                    b.HasOne("AegisScore.Domain.AssessmentScope", null)
                        .WithMany("Answers")
                        .HasForeignKey("AssessmentScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AegisScore.Domain.AssessmentScope", b =>
                {
                    b.HasOne("AegisScore.Domain.Assessment", null)
                        .WithMany("Scopes")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AegisScore.Domain.AssessmentTask", b =>
                {
                    b.HasOne("AegisScore.Domain.AssessmentScope", null)
                        .WithMany("Tasks")
                        .HasForeignKey("AssessmentScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AegisScore.Domain.Asset", b =>
                {
                    b.HasOne("AegisScore.Domain.BusinessProcess", "BusinessProcess")
                        .WithMany("Assets")
                        .HasForeignKey("BusinessProcessId");

                    b.OwnsOne("AegisScore.Domain.BusinessImpactProfile", "BusinessImpact", b1 =>
                        {
                            b1.Property<Guid>("AssetId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Availability")
                                .HasColumnType("integer");

                            b1.Property<int>("Confidentiality")
                                .HasColumnType("integer");

                            b1.Property<int>("Financial")
                                .HasColumnType("integer");

                            b1.Property<int>("Integrity")
                                .HasColumnType("integer");

                            b1.Property<int>("Operational")
                                .HasColumnType("integer");

                            b1.Property<int?>("RecoveryPointObjectiveMinutes")
                                .HasColumnType("integer");

                            b1.Property<int?>("RecoveryTimeObjectiveMinutes")
                                .HasColumnType("integer");

                            b1.Property<int>("Regulatory")
                                .HasColumnType("integer");

                            b1.Property<int>("Reputational")
                                .HasColumnType("integer");

                            b1.HasKey("AssetId");

                            b1.ToTable("Assets");

                            b1.WithOwner()
                                .HasForeignKey("AssetId");
                        });

                    b.Navigation("BusinessImpact");

                    b.Navigation("BusinessProcess");
                });

            modelBuilder.Entity("AegisScore.Domain.AssetDependency", b =>
                {
                    b.HasOne("AegisScore.Domain.Asset", "SourceAsset")
                        .WithMany()
                        .HasForeignKey("SourceAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AegisScore.Domain.Asset", "TargetAsset")
                        .WithMany()
                        .HasForeignKey("TargetAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceAsset");

                    b.Navigation("TargetAsset");
                });

            modelBuilder.Entity("AegisScore.Domain.AssetThreatExposure", b =>
                {
                    b.HasOne("AegisScore.Domain.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AegisScore.Domain.Threat", "Threat")
                        .WithMany()
                        .HasForeignKey("ThreatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Threat");
                });

            modelBuilder.Entity("AegisScore.Domain.BlastRadiusAssessment", b =>
                {
                    b.HasOne("AegisScore.Domain.Asset", "RootAsset")
                        .WithMany()
                        .HasForeignKey("RootAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AegisScore.Domain.Threat", "ScenarioThreat")
                        .WithMany()
                        .HasForeignKey("ScenarioThreatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RootAsset");

                    b.Navigation("ScenarioThreat");
                });

            modelBuilder.Entity("AegisScore.Domain.BlastRadiusImpactNode", b =>
                {
                    b.HasOne("AegisScore.Domain.BlastRadiusAssessment", "Assessment")
                        .WithMany("ImpactedNodes")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AegisScore.Domain.Asset", "ImpactedAsset")
                        .WithMany()
                        .HasForeignKey("ImpactedAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("ImpactedAsset");
                });

            modelBuilder.Entity("AegisScore.Domain.BusinessProcess", b =>
                {
                    b.HasOne("AegisScore.Domain.Tenant", null)
                        .WithMany("Processes")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AegisScore.Domain.BusinessUnit", b =>
                {
                    b.HasOne("AegisScore.Domain.Tenant", null)
                        .WithMany("BusinessUnits")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AegisScore.Domain.ConnectorConfig", b =>
                {
                    b.HasOne("AegisScore.Domain.Tenant", null)
                        .WithMany("Connectors")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AegisScore.Domain.DocumentControlMapping", b =>
                {
                    b.HasOne("AegisScore.Domain.GovernanceDocument", null)
                        .WithMany("ControlMappings")
                        .HasForeignKey("GovernanceDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AegisScore.Domain.Evidence", b =>
                {
                    b.HasOne("AegisScore.Domain.AssessmentScope", null)
                        .WithMany("Evidence")
                        .HasForeignKey("AssessmentScopeId");
                });

            modelBuilder.Entity("AegisScore.Domain.GrcInterviewMessage", b =>
                {
                    b.HasOne("AegisScore.Domain.GrcInterviewSession", null)
                        .WithMany("Messages")
                        .HasForeignKey("GrcInterviewSessionId");
                });

            modelBuilder.Entity("AegisScore.Domain.MaturityLevel", b =>
                {
                    b.HasOne("AegisScore.Domain.FrameworkVersion", null)
                        .WithMany("MaturityLevels")
                        .HasForeignKey("FrameworkVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AegisScore.Domain.NistCategory", b =>
                {
                    b.HasOne("AegisScore.Domain.NistFunction", "Function")
                        .WithMany("Categories")
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Function");
                });

            modelBuilder.Entity("AegisScore.Domain.NistFunction", b =>
                {
                    b.HasOne("AegisScore.Domain.FrameworkVersion", null)
                        .WithMany("Functions")
                        .HasForeignKey("FrameworkVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AegisScore.Domain.NistSubcategory", b =>
                {
                    b.HasOne("AegisScore.Domain.NistCategory", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AegisScore.Domain.Question", b =>
                {
                    b.HasOne("AegisScore.Domain.NistSubcategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("AegisScore.Domain.RiskEvaluation", b =>
                {
                    b.HasOne("AegisScore.Domain.Risk", null)
                        .WithMany("Evaluations")
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AegisScore.Domain.SubcategoryEvaluation", b =>
                {
                    b.HasOne("AegisScore.Domain.AssessmentScope", null)
                        .WithMany("Evaluations")
                        .HasForeignKey("AssessmentScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AegisScore.Domain.NistSubcategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("AegisScore.Domain.TenantControlState", b =>
                {
                    b.HasOne("AegisScore.Domain.NistSubcategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("AegisScore.Domain.UserRefreshToken", b =>
                {
                    b.HasOne("AegisScore.Domain.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AegisScore.Domain.Assessment", b =>
                {
                    b.Navigation("Scopes");
                });

            modelBuilder.Entity("AegisScore.Domain.AssessmentScope", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Evaluations");

                    b.Navigation("Evidence");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AegisScore.Domain.BlastRadiusAssessment", b =>
                {
                    b.Navigation("ImpactedNodes");
                });

            modelBuilder.Entity("AegisScore.Domain.BusinessProcess", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("AegisScore.Domain.FrameworkVersion", b =>
                {
                    b.Navigation("Functions");

                    b.Navigation("MaturityLevels");
                });

            modelBuilder.Entity("AegisScore.Domain.GovernanceDocument", b =>
                {
                    b.Navigation("ControlMappings");
                });

            modelBuilder.Entity("AegisScore.Domain.GrcInterviewSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AegisScore.Domain.NistCategory", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("AegisScore.Domain.NistFunction", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("AegisScore.Domain.Risk", b =>
                {
                    b.Navigation("ActionPlans");

                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("AegisScore.Domain.Tenant", b =>
                {
                    b.Navigation("BusinessUnits");

                    b.Navigation("Connectors");

                    b.Navigation("Processes");
                });

            modelBuilder.Entity("AegisScore.Domain.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
